name: duckdbless_reqs
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Run duckdbless setup
      run: |
         chmod +x ./scripts/duckdb-less_packages.sh
         ./scripts/duckdb-less_packages.sh
         cat scripts/duckdbless_requirements.txt
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
